Traceback (most recent call last):
  File "/home/linkface/software/anaconda3/envs/pytorchlatest/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 436, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/linkface/software/anaconda3/envs/pytorchlatest/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 323, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/linkface/software/anaconda3/envs/pytorchlatest/lib/python3.6/site-packages/ray/worker.py", line 2195, in get
    raise value
ray.exceptions.RayTaskError: [36mray_RayModel:train()[39m (pid=10241, host=GPU-239)
  File "/home/linkface/software/anaconda3/envs/pytorchlatest/lib/python3.6/site-packages/ray/tune/trainable.py", line 150, in train
    result = self._train()
  File "/data/zwy/hack_pba_tensorflow/pba/train.py", line 31, in _train
    train_acc, val_acc = self.trainer.run_model(self._iteration)
  File "/data/zwy/hack_pba_tensorflow/pba/model.py", line 413, in run_model
    if self.hparams.validation_size > 0:
AttributeError: 'HParams' object has no attribute 'validation_size'

